services:
  api:
    image: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # uncomment next two lines if using a .env file with custom variables
    # env_file:
    #   - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - SESSION_SECRET=your_session_secret
      - OPENAI_API_KEY=sk-your_openai_api_key
      - MAPBOX_TOKEN=pk.your_mapbox_token
    volumes:
      - ./backend/src:/app/src

  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    # uncomment next two lines if using a .env file with custom variables
    # env_file:
    #   - ./frontend/.env
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_MAPBOX_TOKEN=pk.your_mapbox_token
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
