services:
  api:
    image: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
