FROM node:20.10-alpine

ENV NODE_ENV=test

WORKDIR /app

# add package.json and package-lock.json to the container
ADD package.json package-lock.json ./

# Install dependencies
RUN npm install

# Add the rest of the files
ADD bin ./bin
ADD jest.migration.config.js ./jest.migration.config.js
ADD migrations ./migrations

# Run the app
CMD ["sh", "-c", "tail -f /dev/null"]