@startuml Adding a book
start
:User, who is a library owner, wants to add a new book to their library;
if (The same book is on the site already?) then (yes)
:They click the "Copy to Library" button on the book's page;
:They verify the details, editing if necessary;
:They choose a library to add the book to;
else (no)
:They click "Add New Book" on the library's page;
:They input the details in a form and submit it;
endif
:Book is added to the library;
stop
@enduml