@startuml Adding a book
start
:User, who is a library owner, wants to add a new copy to their library;
:They gather the book details;
:They put the details info a form to look the book up;
:Book details matching the query are fetched from the Open Library API;
:User selects the book from the list of options returned;
if (Book exists in DB?) then (yes)
else (no)
  :Book info is inserted into the database to keep track across different libraries;
endif
:Book is added to the library;
stop
@enduml