name: "Run backend tests, check linting and package version on PR"

on:
  pull_request:
    paths:
      - "backend/**"

jobs:
  check-run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "20.3"
      - name: Install dependencies
        run: npm install
      - name: Check npm version bump
        uses: EndBug/version-check@v2.1.1
        with:
          file-name: ./backend/package.json
        id: checkVersion
      - name: Version change not detected
        if: steps.checkVersion.outputs.changed == 'false'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Uh oh, someone forgot to bump the backend package version!')
      - name: Check ESLint
        run: npm run eslint:check
      - name: Run tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          GCLOUD_STORAGE_BUCKET: ${{ secrets.GCLOUD_STORAGE_BUCKET }}
        run: npm run test
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/backend/coverage/lcov.info:lcov
