on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  run-tests-and-publish-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: "20.3"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          GCLOUD_STORAGE_BUCKET: ${{ secrets.GCLOUD_STORAGE_BUCKET }}
        run: npm run test
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/backend/coverage/lcov.info:lcov
